# Generated by Django 5.1.6 on 2025-05-16 15:48

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogs', '0003_warehouse_latitude_warehouse_longitude'),
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('ACTIVO', 'activo'), ('INACTIVO', 'inactivo')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='LoadCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('ACTIVO', 'activo'), ('INACTIVO', 'inactivo')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('operation', models.CharField(choices=[('ENTRADA', 'entrada'), ('SALIDA', 'salida')], max_length=30)),
                ('is_virtual', models.BooleanField()),
                ('status', models.CharField(choices=[('ACTIVO', 'activo'), ('INACTIVO', 'inactivo')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='TransportationCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('ACTIVO', 'activo'), ('INACTIVO', 'inactivo')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_date', models.DateTimeField(auto_now_add=True)),
                ('volume', models.IntegerField()),
                ('weight', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('total_packages', models.IntegerField()),
                ('total_pallets', models.IntegerField()),
                ('carrier_name', models.CharField(max_length=100)),
                ('carrier_license_plates', models.CharField(max_length=100)),
                ('carrier_driver', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('CAPTURA', 'en captura'), ('SOLICITADA', 'solicitada'), ('CONFIRMADA', 'confirmada'), ('ENTREGADA', 'entregada'), ('CANCELADA', 'cancelada'), ('RECHAZADA', 'rechazada')], max_length=10)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogs.company')),
                ('request_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogs.supplier')),
                ('appointment_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointments.appointmentcategory')),
                ('load_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointments.loadcategory')),
                ('transportation_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointments.transportationcategory')),
            ],
        ),
        migrations.CreateModel(
            name='AppointmentDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packages', models.IntegerField()),
                ('weight', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('delivered_packages', models.IntegerField()),
                ('rejected_packages', models.IntegerField()),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointments.appointment')),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.documento')),
            ],
        ),
    ]
