# Generated by Django 5.1.6 on 2025-06-10 15:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [

        migrations.CreateModel(
            name='AppointmentConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_date', models.DateTimeField(
                    auto_now_add=True, verbose_name='Fecha Asignada')),
                ('timespan', models.IntegerField(verbose_name='Tiempo asignado')),
                ('confirmation_date', models.DateTimeField(
                    auto_now_add=True, verbose_name='Fecha de confirmación')),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 to='appointments.appointment', verbose_name='Cita')),
                ('confirming_user', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 to='appointments.platform', verbose_name='Andén')),
            ],
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_type', models.CharField(
                    max_length=1000, verbose_name='Tipo de Incidencia')),
                ('comment', models.TextField(
                    max_length=100, verbose_name='Comentarios')),
                ('reporting_datetime', models.DateTimeField(
                    auto_now_add=True, verbose_name='Fecha de registro')),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 to='appointments.appointment', verbose_name='Cita')),
                ('reporting_user', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IncidentEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.TextField(
                    max_length=100, verbose_name='Archivo')),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 to='appointments.incident', verbose_name='Incidencia')),
            ],
        ),
    ]
