# Generated by Django 5.1.6 on 2025-06-10 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_rename_documento_appointmentdocuments_document_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='comment',
            field=models.TextField(max_length=100, verbose_name='Comentario'),
        ),
    ]
