# Generated by Django 5.1.6 on 2025-06-10 22:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_alter_incident_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentconfirmation',
            name='appointment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointments.appointment', verbose_name='Cita '),
        ),
        migrations.AlterField(
            model_name='incident',
            name='appointment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointments.appointment', verbose_name='Cita '),
        ),
        migrations.AlterField(
            model_name='incident',
            name='comment',
            field=models.TextField(max_length=100, verbose_name='Comentarios'),
        ),
        migrations.AlterField(
            model_name='incidentevidence',
            name='incident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointments.incident', verbose_name='Incidencia '),
        ),
    ]
