# Generated by Django 5.1.6 on 2025-06-10 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_alter_appointmentconfirmation_appointment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentconfirmation',
            name='appointment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointments.appointment', verbose_name='Cita'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='appointment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointments.appointment', verbose_name='Cita'),
        ),
        migrations.AlterField(
            model_name='incidentevidence',
            name='incident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointments.incident', verbose_name='Incidencia'),
        ),
    ]
