# Generated by Django 5.1.6 on 2025-03-05 15:03

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=100)),
                ('exterior_number', models.CharField(max_length=10)),
                ('interior_number', models.CharField(max_length=10)),
                ('reference', models.CharField(max_length=200)),
                ('postcode', models.CharField(max_length=5)),
                ('neighborhood', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('short_name', models.CharField(max_length=20)),
                ('rfc', models.CharField(max_length=13, validators=[django.core.validators.MinLengthValidator(12)])),
                ('image_logo', models.CharField(max_length=250)),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='catalogs.address')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_supplier_id', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('short_name', models.CharField(max_length=20)),
                ('rfc', models.CharField(max_length=13, validators=[django.core.validators.MinLengthValidator(12)])),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='catalogs.address')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogs.company')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=50)),
                ('mpn', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('packing_unit', models.CharField(max_length=50)),
                ('master_package', models.IntegerField()),
                ('inner_package', models.IntegerField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogs.company')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogs.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_warehouse_id', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='catalogs.address')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogs.company')),
            ],
        ),
    ]
