# Generated by Django 5.1.6 on 2025-05-21 23:06

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogs', '0003_warehouse_latitude_warehouse_longitude'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(max_length=200)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('totalPeso', models.IntegerField()),
                ('totalBultos', models.IntegerField()),
                ('compania', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogs.company')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogs.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie', models.CharField(max_length=100)),
                ('folio', models.CharField(max_length=100)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('subtotal', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=12)),
                ('impuestos', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=12)),
                ('total', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=12)),
                ('uuid', models.UUIDField()),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.documento')),
            ],
        ),
        migrations.CreateModel(
            name='Factura_archivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('nombre', models.CharField(max_length=250)),
                ('tipo', models.CharField(max_length=5)),
                ('ruta', models.CharField(max_length=200)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.factura')),
            ],
        ),
        migrations.CreateModel(
            name='Factura_detalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=50)),
                ('claveProductoSat', models.CharField(max_length=10)),
                ('claveUnidadSat', models.CharField(max_length=5)),
                ('unidadSat', models.CharField(max_length=5)),
                ('descripcion', models.CharField(max_length=200)),
                ('valorUnitario', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=12)),
                ('descuento', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=12)),
                ('importe', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=12)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.factura')),
            ],
        ),
        migrations.CreateModel(
            name='Desglose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bulto', models.IntegerField()),
                ('cantidad_orden', models.IntegerField()),
                ('cantidad_factura', models.IntegerField(default=0)),
                ('peso_unitario_factura', models.DecimalField(decimal_places=2, default=Decimal('0.0000'), max_digits=8)),
                ('order_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.orderdetail')),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.documento')),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.factura')),
                ('factura_detalle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.factura_detalle')),
            ],
        ),
    ]
