# Generated by Django 5.1.6 on 2025-06-10 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='ordenes',
            field=models.ManyToManyField(to='orders.order'),
        ),
    ]
