# Generated by Django 5.1.6 on 2025-03-25 17:58

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogs', '0002_alter_warehouse_company_warehouse_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=20)),
                ('is_season', models.BooleanField(default=False)),
                ('is_prepaid', models.BooleanField(default=False)),
                ('category', models.CharField(max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=12)),
                ('tax_value', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=12)),
                ('total', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=12)),
                ('status', models.CharField(max_length=20)),
                ('date_ordered', models.DateField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogs.company')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogs.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.DecimalField(decimal_places=4, max_digits=12)),
                ('quantity', models.IntegerField()),
                ('subtotal', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=12)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('tax_value', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=12)),
                ('total', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=12)),
                ('packing_unit', models.CharField(max_length=20)),
                ('master_package', models.IntegerField()),
                ('inner_package', models.IntegerField()),
                ('no_charge', models.BooleanField(default=False)),
                ('description', models.TextField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogs.product')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogs.warehouse')),
            ],
        ),
    ]
